// Support co-pilot runtime. For each new Freshdesk ticket:
//   1. Pull conversation context (subject + body + thread)
//   2. Apply short-circuits (spam, exact-template, structured bug) BEFORE any LLM
//   3. RAG: keyword filter on skills, then Claude rerank for top-5 most relevant
//   4. Decide if Stripe lookup is warranted (billing/subscription/refund intent)
//   5. Drafting prompt: ticket + retrieved skills + Stripe context + tool schemas
//   6. Persist as agent_runs row in `pending` status — the human reviews it in /agent
//
// Note: the LLM is called via the existing src/lib/extract/llm.ts wrapper which
// already routes between Anthropic API and the local CLI based on env. The
// tool-calling interface here is JSON-mode (we ask Claude to output structured
// JSON) rather than the SDK's native tools API — keeps the wrapper simple and
// works with both API and CLI backends.

import { llmCall, parseJsonBlock } from "@/lib/extract/anthropic";
import type { Skill, Workspace } from "@/lib/db";
import type { FreshdeskTicket, FreshdeskConversation } from "@/lib/freshdesk";
import { buildCompanyContextBlock } from "@/lib/extract/company-context-block";
import {
  renderCatalogForPrompt,
  renderDynamicEndpointsForPrompt,
  type AgentAction,
  type ActionStage,
  type ApprovalLevel,
} from "./tool-catalog";
import { listActiveCustomerEndpoints } from "@/lib/db";

export type AgentToolCall = {
  tool: string;
  args: Record<string, unknown>;
  result?: unknown;
  error?: string;
};

export type AgentDraftResult = {
  decision: "draft" | "spam" | "skip" | "needs_human";
  draft: string | null;
  reasoning: string;
  matchedSkillSlugs: string[];
  toolCalls: AgentToolCall[];
  /** Proposed multi-tool action plan. Phase 1: generated by the LLM, displayed
   * in the reviewer UI, NEVER executed. The reviewer sees what the agent would
   * propose to do across Freshdesk + Stripe + Slack + DB if execution were
   * enabled. Phase 3 will add the actual executor. */
  proposedActions: AgentAction[];
  urgency: "low" | "medium" | "high" | "critical";
  category: string;
  // Short-circuit reason (set when decision came from a non-LLM rule)
  shortCircuit?:
    | "spam_regex"
    | "exact_template_resiliation"
    | "exact_template_relance_paiement"
    | "exact_template_offre_etudiants"
    | null;
};

// ---------- Short-circuit layer (no LLM) ----------

const SPAM_RE =
  /\b(spring|tiktok|sellers?|free ads|launched in|biggest quarter|moving early|aurelia_|découvrez|suivez l|stories|quarterly|spring ad credits|ecommerce trends)\b/i;

const EXACT_TEMPLATE_SUBJECTS: Record<string, AgentDraftResult["shortCircuit"]> = {
  "raison résiliation abonnement": "exact_template_resiliation",
  "relance paiement": "exact_template_relance_paiement",
  "offre étudiants": "exact_template_offre_etudiants",
};

export function detectShortCircuit(ticket: FreshdeskTicket): AgentDraftResult | null {
  const subject = (ticket.subject ?? "").trim();

  // 1. Spam: matched newsletter/promo regex → close, no reply
  if (SPAM_RE.test(subject)) {
    return {
      decision: "spam",
      draft: null,
      reasoning: `Subject matched newsletter/promo pattern (no human reply needed): "${subject.slice(0, 80)}"`,
      matchedSkillSlugs: [],
      toolCalls: [],
      proposedActions: [
        {
          id: "spam_close",
          tool: "freshdesk.set_status",
          args: { status: 5 },
          reason: "Spam pattern detected — close without reply",
          stage: "housekeeping",
          irreversible: false,
          approval: "low",
        },
        {
          id: "spam_tag",
          tool: "freshdesk.add_tag",
          args: { tags: ["spam"] },
          reason: "Tag for tracking + future short-circuit",
          stage: "housekeeping",
          irreversible: false,
          approval: "low",
        },
      ],
      urgency: "low",
      category: "spam",
      shortCircuit: "spam_regex",
    };
  }

  // 2. Exact subject templates: pre-validated reply exists, no LLM needed
  const tpl = EXACT_TEMPLATE_SUBJECTS[subject.toLowerCase()];
  if (tpl) {
    return {
      decision: "draft",
      draft: null, // filled by template engine downstream
      reasoning: `Exact-template match: "${subject}" → use pre-validated template (no LLM call needed).`,
      matchedSkillSlugs: [],
      toolCalls: [],
      proposedActions: [],
      urgency: "medium",
      category: "template",
      shortCircuit: tpl,
    };
  }

  return null;
}

// ---------- RAG: keyword filter + LLM rerank ----------

function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .split(/[^a-z0-9]+/)
    .filter((w) => w.length >= 3);
}

const STOPWORDS = new Set([
  "the", "and", "for", "with", "that", "this", "from", "have", "has", "are", "was", "but",
  "les", "des", "une", "pour", "que", "qui", "dans", "vous", "votre", "nous", "notre", "est",
  "mon", "ma", "mes", "son", "sa", "ses", "comme", "avec", "sur", "par", "plus", "moins",
]);

function keywordOverlap(ticketTokens: Set<string>, skill: Skill): number {
  const skillTokens = new Set(
    tokenize(`${skill.title} ${skill.trigger ?? ""} ${skill.steps_md?.slice(0, 500) ?? ""}`),
  );
  let overlap = 0;
  for (const t of ticketTokens) {
    if (STOPWORDS.has(t)) continue;
    if (skillTokens.has(t)) overlap += 1;
  }
  return overlap;
}

export function selectCandidateSkills(ticket: FreshdeskTicket, allSkills: Skill[], topN = 20): Skill[] {
  const ticketText = `${ticket.subject ?? ""} ${ticket.description_text ?? ""}`;
  const tokens = new Set(tokenize(ticketText));
  const scored = allSkills
    .filter((s) => s.status !== "superseded")
    .map((s) => ({ skill: s, score: keywordOverlap(tokens, s) }))
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, topN);
  return scored.map((x) => x.skill);
}

// ---------- Drafting (Claude) ----------

export type AgentRuntimeInput = {
  workspace: Workspace;
  ticket: FreshdeskTicket;
  conversation?: FreshdeskConversation[];
  candidateSkills: Skill[];
  // Stripe context — pre-fetched if the ticket smells like billing/subscription
  stripeContext?: string;
  // Slack context — recent messages from nominated dev/ops channels. Gives
  // the LLM grounding to cite real fix timelines, known bugs, ongoing work.
  slackContext?: string;
  apiKey?: string;
};

const DRAFT_SYSTEM = `You are a customer-support co-pilot. For each ticket you produce TWO things:
  1. A draft reply (text the customer will see, after human review).
  2. A proposed action plan — additional tool calls across Freshdesk, Stripe, Slack, and slackmap's internal DB that should happen alongside or instead of the reply.

You will receive:
  - The Freshdesk ticket (subject + body + thread so far)
  - The company's relevant operational skills (procedures, policies)
  - Optional Stripe context (the customer's subscription / invoice state) when the ticket is billing-related
  - Optional Slack context (RECENT dev/ops/bug-support channel chatter) so you can cite real fix timelines, known bugs, ongoing work — without inventing them
  - A catalog of TOOLS you may propose

Output ONLY a single JSON object:
{
  "decision": "draft" | "skip" | "needs_human",
  "draft": "<the actual reply text in the customer's language, OR null>",
  "reasoning": "<one paragraph: what you understood, which skills you used, why this draft + plan is appropriate>",
  "matched_skill_slugs": ["slug1", "slug2"],
  "urgency": "low" | "medium" | "high" | "critical",
  "category": "billing" | "bug" | "subscription_cancel" | "feature_request" | "complaint" | "info_request" | "other",
  "proposed_actions": [
    {
      "id": "<short snake_case id unique within this plan>",
      "tool": "<one of the catalog tool names>",
      "args": { ... matching the tool's args schema ... },
      "reason": "<why this action belongs in the plan, grounded in skills/context>",
      "stage": "communication" | "remediation" | "housekeeping" | "memory" | "escalation",
      "irreversible": <true|false>,
      "approval": "low" | "medium" | "high"
    }
  ]
}

RULES FOR THE PLAN:
- The plan is NOT executed automatically. A human reviews it action-by-action. You can propose ambitious plans — the reviewer will toggle off what isn't appropriate.
- If you write a draft (decision="draft" or "needs_human" with a holding response), ALWAYS include a freshdesk.reply action mirroring the draft text. The draft string is the SOURCE OF TRUTH for the reply — the reply action just wraps it.
- Propose stripe.* actions ONLY when (a) a skill explicitly authorises the action OR (b) the Stripe customer context makes the action obviously correct (e.g. customer in 7-day trial requests refund + skill 'refund-within-trial' exists).
- Propose db.record_customer_fact for any reusable cross-ticket signal (customer plan, recent incidents, language preference). Keep facts short and atomic.
- Propose db.feedback_skill with each skill slug you actually grounded the draft on.
- Propose slack.notify_bug_channel ONLY for bug / technical / regression tickets where engineering would benefit from awareness. Skip it for billing / info-request / spam.
- If escalating to a human reviewer for sensitive reasons (legal threat, suspected fraud, multi-customer impact), include db.escalate_explicit with a clear reason.
- For spam/test/empty (decision="skip"), include freshdesk.set_status (5=closed) + freshdesk.add_tag (["spam"]) and NOTHING else.

Rules:
- Output the draft in the SAME language as the customer wrote (French if French, English if English).
- Match the company's tone from the skills (concise, direct, warm).
- Cite skills by their slug in matched_skill_slugs (only if you actually grounded the draft on them).

CRITICAL — always produce a USEFUL draft, even when full resolution requires a human:
- For genuine support tickets, ALWAYS write a draft. It's a starting point for the reviewer, not the final word.
- When skills fully cover the ticket → draft the actual solution. decision="draft".
- When skills only partially cover OR more diagnostic info is needed → draft a SAFE HOLDING RESPONSE:
    1) acknowledge the issue in the customer's tone
    2) ask the specific clarifying questions needed (device, OS, exact error, screenshots, account email if missing)
    3) commit to a next step ("our team is checking", "I'll come back to you within Xh") — only commit to timing if the skills or Slack context support it; otherwise stay vague ("dès que possible")
   Set decision="needs_human" so the reviewer knows it requires escalation, but FILL draft with the holding response. NEVER return draft=null on a real ticket.
- Only return draft=null when the ticket is genuinely empty/spam/test (decision="skip").

Never make stuff up:
- NEVER invent policy or commitments not supported by the skills.
- NEVER promise refunds, cancellations, or specific outcomes unless a skill or the Stripe/Slack context explicitly authorises it.
- NEVER cite fix timelines unless the Slack context shows them. If unsure, write "our engineering team is investigating".

Length: drafts under 200 words. The reviewer will edit before sending.

## Tools available for the action plan
${renderCatalogForPrompt()}`;

function buildSkillsBlock(skills: Skill[]): string {
  if (skills.length === 0) return "(no matching skills found in the catalog)";
  return skills
    .slice(0, 5)
    .map(
      (s, i) =>
        `### Skill ${i + 1}: ${s.slug}\n` +
        `Title: ${s.title}\n` +
        (s.trigger ? `Trigger: ${s.trigger}\n` : "") +
        (s.steps_md ? `Steps:\n${s.steps_md.slice(0, 800)}\n` : "") +
        (s.decision_criteria ? `Decision criteria: ${s.decision_criteria}\n` : ""),
    )
    .join("\n\n");
}

function buildTicketBlock(ticket: FreshdeskTicket, conversation: FreshdeskConversation[] = []): string {
  const reqEmail = ticket.requester?.email ? `\nRequester email: ${ticket.requester.email}` : "";
  const convBlock = conversation
    .filter((c) => c.body_text && !c.private)
    .slice(0, 5)
    .map((c, i) => `--- Reply ${i + 1} ${c.incoming ? "(customer)" : "(agent)"} ---\n${c.body_text!.slice(0, 800)}`)
    .join("\n");
  return [
    `### Ticket #${ticket.id}`,
    `Subject: ${ticket.subject}`,
    reqEmail.trim(),
    `Body:\n${(ticket.description_text ?? "").slice(0, 1500)}`,
    convBlock ? `\nConversation so far:\n${convBlock}` : "",
  ]
    .filter(Boolean)
    .join("\n");
}

export async function draftReply(input: AgentRuntimeInput): Promise<AgentDraftResult> {
  // Always check short-circuits first — saves an LLM call for ~30% of volume.
  const sc = detectShortCircuit(input.ticket);
  if (sc) return sc;

  // Pull active customer endpoints registered for this workspace — they
  // become dynamic tools the LLM can propose. Top 10 by coverage to bound
  // prompt size.
  const activeEndpoints = await listActiveCustomerEndpoints(input.workspace.id, {
    limit: 10,
  }).catch(() => []);

  const system =
    buildCompanyContextBlock(input.workspace) +
    DRAFT_SYSTEM +
    renderDynamicEndpointsForPrompt(
      activeEndpoints.map((e) => ({
        name: e.name,
        description: e.description,
        why: e.why,
        method: e.method,
        url_template: e.url_template,
        request_schema: e.request_schema,
        estimated_ticket_coverage_pct: e.estimated_ticket_coverage_pct,
      })),
    );

  const userMessage =
    `${buildTicketBlock(input.ticket, input.conversation)}\n\n` +
    `## Relevant skills from the company brain\n\n${buildSkillsBlock(input.candidateSkills)}\n` +
    (input.stripeContext ? `\n## Stripe customer context\n${input.stripeContext}\n` : "") +
    (input.slackContext ? `\n## Recent Slack context — dev/ops discussions\n${input.slackContext}\n` : "");

  const text = await llmCall({
    system,
    userMessage,
    // Bumped from 1500 → 3500. The JSON now carries draft + reasoning +
    // matched_skill_slugs + urgency + category + proposed_actions[] (5-10
    // actions × ~100 tokens each). At 1500 the response truncated mid-JSON,
    // parseJsonBlock failed, and every draft fell back to "LLM output
    // couldn't be parsed — needs_human" with no actions.
    maxTokens: 3500,
    model: "extract",
    apiKey: input.apiKey,
  });

  type LlmOut = {
    decision?: AgentDraftResult["decision"];
    draft?: string | null;
    reasoning?: string;
    matched_skill_slugs?: string[];
    urgency?: AgentDraftResult["urgency"];
    category?: string;
    proposed_actions?: unknown[];
  };

  let parsed: LlmOut;
  try {
    parsed = parseJsonBlock<LlmOut>(text);
  } catch {
    return {
      decision: "needs_human",
      draft: null,
      reasoning: "LLM output couldn't be parsed as JSON — defer to human.",
      matchedSkillSlugs: [],
      toolCalls: [],
      proposedActions: [],
      urgency: "medium",
      category: "other",
      shortCircuit: null,
    };
  }

  return {
    decision: parsed.decision ?? "needs_human",
    draft: typeof parsed.draft === "string" ? parsed.draft : null,
    reasoning: parsed.reasoning ?? "",
    matchedSkillSlugs: Array.isArray(parsed.matched_skill_slugs) ? parsed.matched_skill_slugs : [],
    toolCalls: [],
    proposedActions: sanitizeProposedActions(parsed.proposed_actions),
    urgency: parsed.urgency ?? "medium",
    category: parsed.category ?? "other",
    shortCircuit: null,
  };
}

/**
 * Loose validator for the LLM's proposed_actions output. Drops anything that
 * doesn't have the minimum required shape rather than throwing — we'd rather
 * persist a partial plan than reject the whole draft over a malformed action.
 */
function sanitizeProposedActions(raw: unknown): AgentAction[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .filter((a): a is Record<string, unknown> => typeof a === "object" && a !== null)
    .map((a, idx) => {
      const id = typeof a.id === "string" && a.id.length > 0 ? a.id : `act_${idx}`;
      const tool = typeof a.tool === "string" ? a.tool : "";
      const args = typeof a.args === "object" && a.args !== null ? (a.args as Record<string, unknown>) : {};
      const reason = typeof a.reason === "string" ? a.reason : "";
      const stage: ActionStage =
        a.stage === "communication" ||
        a.stage === "remediation" ||
        a.stage === "housekeeping" ||
        a.stage === "memory" ||
        a.stage === "escalation"
          ? a.stage
          : "housekeeping";
      const irreversible = a.irreversible === true;
      const approval: ApprovalLevel =
        a.approval === "low" || a.approval === "high" ? a.approval : "medium";
      return {
        id,
        tool: tool as AgentAction["tool"],
        args,
        reason,
        stage,
        irreversible,
        approval,
      };
    })
    .filter((a) => a.tool.length > 0);
}
