import { NextRequest, NextResponse } from "next/server";
import { zipSync, strToU8 } from "fflate";
import { db, listSkills } from "@/lib/db";
import { renderSkillMarkdown } from "@/lib/extract/skills";

// Bundles all skills as a Claude Code plugin-compatible zip:
//
//   <workspace-slug>-skills/
//     plugin.json
//     README.md
//     skills/
//       <slug>/SKILL.md           (one folder per skill)
//
// The user can drop this in ~/.claude/plugins/ or ship as a Claude plugin.
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;

  const { data: ws } = await db()
    .from("workspaces")
    .select("id, slack_team_name, slack_team_domain")
    .eq("id", id)
    .maybeSingle();
  if (!ws) return new NextResponse("not found", { status: 404 });

  const allSkills = await listSkills(id);
  const skills = allSkills.filter((s) => s.status === "active");
  const teamDomain = (ws.slack_team_domain as string | null) ?? null;
  const teamSlug = (ws.slack_team_name as string).toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const bundleName = `${teamSlug}-skills`;

  const files: Record<string, Uint8Array> = {};

  files[`${bundleName}/plugin.json`] = strToU8(
    JSON.stringify(
      {
        name: bundleName,
        version: "0.1.0",
        description: `Executable skills extracted from ${ws.slack_team_name} Slack`,
        generated_at: new Date().toISOString(),
        skills_count: skills.length,
      },
      null,
      2,
    ),
  );

  files[`${bundleName}/README.md`] = strToU8(
    [
      `# ${ws.slack_team_name} — Company Brain skills`,
      "",
      `Generated by Slackmap on ${new Date().toISOString().split("T")[0]}.`,
      `${skills.length} skills extracted from Slack history.`,
      "",
      "## Install (Claude Code)",
      "",
      "Drop this folder into `~/.claude/plugins/` or commit to a repo and",
      "`claude plugin install <repo>`.",
      "",
      "## Skills",
      "",
      ...skills.map((s) => `- **${s.title}** (\`${s.slug}\`) — ${s.type}, ${s.source_count} sources, confidence ${Math.round(s.confidence * 100)}%`),
      "",
    ].join("\n"),
  );

  for (const s of skills) {
    const md = renderSkillMarkdown({
      slug: s.slug,
      title: s.title,
      type: s.type,
      trigger: s.trigger,
      steps_md: s.steps_md,
      decision_criteria: s.decision_criteria,
      escalation: s.escalation,
      citations: s.citations,
      confidence: s.confidence,
      source_count: s.source_count,
      last_observed_at: s.last_observed_at,
      workspace_team_domain: teamDomain,
    });
    files[`${bundleName}/skills/${s.slug}/SKILL.md`] = strToU8(md);
  }

  const zipped = zipSync(files, { level: 6 });

  return new NextResponse(new Uint8Array(zipped), {
    headers: {
      "content-type": "application/zip",
      "content-disposition": `attachment; filename="${bundleName}.zip"`,
    },
  });
}
